spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:postgresql://44.210.16.222:5432/ecommerce
    username: ecommerce
    password: ecommerce
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: America/Mexico_City

